language: node_js
cache: yarn
node_js:
  - node
  - "10"
  - "8"
  - "6"
services:
  - redis-server
addons:
  postgresql: '9.4'
before_script:
  - psql -c 'create database logux_test;' -U postgres
git:
  depth: 5
